apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://host.docker.internal:8086
    uid: "P951FEA4DE68E13C5"
    jsonData:
      version: Flux              # Use Flux query language (InfluxDB v2)
      organization: ${DOCKER_INFLUXDB_INIT_ORG}    # InfluxDB organization
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}    # InfluxDB bucket
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

  - name: Loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    uid: "P8E80F9AEF21F6940"
    jsonData:
      maxLines: 1000   # max lines to return (default 1000)
      # timeout: 60      # query timeout in seconds (default 60)

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    uid: "PBFA97CFB590B2093"
    isDefault: true





# apiVersion: 1

# datasources:
#   # ------------------------------------------------------------
#   # Prometheus datasource
#   # ------------------------------------------------------------
#   - name: Prometheus
#     type: prometheus
#     uid: prometheus
#     orgId: 1
#     url: http://host.docker.internal:9090  # or ${PROMETHEUS_URL}
#     access: proxy
#     isDefault: true
#     version: 1
#     editable: true
#     # jsonData, secureJsonData, etc. can be expanded as needed

#   # ------------------------------------------------------------
#   # Loki datasource
#   # ------------------------------------------------------------
#   - name: loki
#     type: loki
#     uid: loki
#     orgId: 1
#     url: http://host.docker.internal:3100  # or ${LOKI_URL}
#     access: proxy
#     isDefault: false
#     version: 1
#     editable: true

#   # ------------------------------------------------------------
#   # InfluxDB v2 datasource (Flux)
#   # ------------------------------------------------------------
#   - name: influxdb
#     type: influxdb
#     uid: influxdb
#     orgId: 1
#     url: http://host.docker.internal:8086  # or ${INFLUXDB_URL}
#     access: proxy
#     isDefault: false
#     version: 1
#     editable: true

#     # Influx v2/Flux–specific settings
#     jsonData:
#       # “Flux” signals we are using the newer InfluxDB v2 / Flux engine
#       version: Flux


#       # organization: ${INFLUXDB_ORG}
#       # defaultBucket: ${INFLUXDB_BUCKET}
#       organization: "DataForge"
#       defaultBucket: "mqtt"
      
#       minTimeInterval: "10s"
#       maxSeries: 1000

#     secureJsonData:
#       # You can also do ${INFLUXDB_TOKEN} to pull from env var
#       token: "configured"
